### ISSUE TITLE
Nice control, but a button perhaps

### ISSUE THREAD

**Issue by cfairweather** [nverinaud/NVUIGradientButton#4]
Allo,
First off, kudos for making it ARC compatible. Refreshing well built control.
Improvement request:
Perhaps the project would better be named NVUIGradientControl since it does not actually subclass UIButton; the alternative is to change the control to a button. 
This means that a user can't place a button on the storyboard, configure it, and then change the class. All of the settings could easily be derived from the button itself after the user has configured it on the storyboard.
Just a thought. Thanks for contributing to the community

**Comment by nverinaud** [comment]
Thanks for your support.
Nope, not a UIButton subclass sorry :-)
