### ISSUE TITLE
Drawing crashed with autolayout enable

### ISSUE THREAD

**Issue by lauhw** [nverinaud/NVUIGradientButton#7]
Thanks for sharing the code. I have tested it with a new project and found out that if autolayout was enabled in storyboard, the drawing will crash. If I disabled the autolayout, the button is working perfectly. Is there anyway to make it works in autolayout mode?

**Comment by nverinaud** [comment]
And thank you for reporting issues :)
I'll check this one as soon as possible, could you give me the stack trace ?
It's a bit weird because view drawing code is not tied to layout...

**Comment by lauhw** [comment]
Hi,

When auto-layout was enabled, the UIView (ie, the gradient button) will
have 4 layout constraints which I can't remove it. The following message
will appear in the console:

2013-07-02 21:37:00.784 TestButton[374:11303] Unable to simultaneously
satisfy constraints.
    Probably at least one of the constraints in the following list is one
you don't want. Try this: (1) look at each constraint and try to figure out
which you don't expect; (2) find the code that added the unwanted
constraint or constraints and fix it. (Note: If you're seeing
NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the
documentation for the UIView property
translatesAutoresizingMaskIntoConstraints)
(
    "<NSLayoutConstraint:0x88777e0
V:[NVUIGradientButton:0x8873510]-(341)-|   (Names: '|':UIView:0x8874d40 )>",
    "<NSLayoutConstraint:0x88777a0
V:|-(152)-[NVUIGradientButton:0x8873510]   (Names: '|':UIView:0x8874d40 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x717a9c0 h=--& v=--&
V:[UIView:0x8874d40(460)]>"
)

Will attempt to recover by breaking constraint
<NSLayoutConstraint:0x88777e0 V:[NVUIGradientButton:0x8873510]-(341)-|
(Names: '|':UIView:0x8874d40 )>

Break on objc_exception_throw to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView
listed in <UIKit/UIView.h> may also be helpful.

Thanks & Regards,

# LAU HON WAN

Mobile: 6-012-303-2330
Skype ID: lauhw2000
Gmail Chat ID: lau@ciysys.com
Service: ASP.NET http://asp.net/ web development, system design &
database design/optimization.
Website: http://www.ciysys.com

**Comment by lauhw** [comment]
I found the solution where the problem is not related to the gradient
button. The UIView must have Width & Height constraints (you need to add
these 2 manually).

http://www.raywenderlich.com/20897/beginning-auto-layout-part-2-of-2

Thanks & Regards,

# LAU HON WAN

Mobile: 6-012-303-2330
Skype ID: lauhw2000
Gmail Chat ID: lau@ciysys.com
Service: ASP.NET http://asp.net/ web development, system design &
database design/optimization.
Website: http://www.ciysys.com

**Comment by nverinaud** [comment]
Well done ;-) :+1:
