### ISSUE TITLE
Implicit conversion of Objective-C pointer type ...

### ISSUE THREAD

**Issue by stefanoAro** [nverinaud/NVUIGradientButton#9]
I encounter two errors:

on this line:
[appearance setBorderColor:[UIColor darkGrayColor]];
I obtain
Implicit conversion of Objective-C pointer type 'UIColor *' to C pointer type 'CGColorRef' (aka 'struct CGColor *') requires a bridged cast

on this line
self.borderColor = [appearance borderColor];
I obtain
Implicit conversion of C pointer type 'CGColorRef' (aka 'struct CGColor *') to Objective-C pointer type 'UIColor *' requires a bridged cast

**Comment by nverinaud** [comment]
Thank you for your feedback.

Unfortunately I can't reproduce the error `:(`.

Could you please tell me which version of Xcode you're using and if you're using ARC ?

Thanks !
